spring.datasource.url=jdbc:sqlserver://localhost;databaseName=CartorioDB;integratedSecurity=true;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Para evitar erros caso o servidor esteja na porta padrao (1433) e instacia padrao.
# O trustServerCertificate=true é importante em ambientes locais para evitar problemas de certificado SSL.

server.port=8080
